- name: Create Internet Gateway
  community.aws.ec2_vpc_igw:
    region: "{{ ec2_region }}"
    vpc_id: "{{ create_vpc.vpc.id }}"
    tags:
      Environment: "{{ ec2_environment }}"
  register: igw
  until: igw is not failed
  retries: 5